### ISSUE TITLE
Translation of "Create new"

### ISSUE THREAD

**Issue by mprofitl** [animaux/lang_german#11]
The English button "Create new" fully means "Create a new entry/association/…". The German translation is not right: "Neu erstellen" means "Create newly" (as a substitute). The proper wording would be "Neue/s/n erstellen" (neuen Link, neuen Bereich, neue Verknüpfung, …). I understand that the different endings make it virtually impossible to get the wording right. What about changing the text to one of these: Neu/Anlegen/Neuer Eintrag/Erstellen?

**Comment by animaux** [comment]
Ich denke das momentane `Neu erstellen` ist noch die flexibelste Variante der genannten Möglichkeiten. Alle anderen Alternativen sind in etwa genauso präzise. Ich sehe da keinen nennenswerten Vorteil das umzubennen. Ich weiß nicht ob @nilshoerrmann dazu was sagen möchte.

Bei Installationen die eine präzisere Benennung benötigten habe ich den Text je nach Bereich entsprechend per `backend_assets` via CSS ersetzt oder ergänzt.

**Comment by nilshoerrmann** [comment]
`Neu erstellen` halte ich auch nach wie vor für einen guten Kompromiss.
