### ISSUE TITLE
Default datetime settings

### ISSUE THREAD

**Issue by nilshoerrmann** [animaux/lang_german#9]
Die deutsche Übersetzung sollte [beim Rücksetzen der Zeitformate](https://github.com/animaux/lang_german/blob/master/extension.driver.php#L93-L105) überprüfen, ob es überhaupt gespeicherte Werte gibt. Es braucht irgendwelche Rückfallwerte, falls es keine gespeicherten Daten gibt.

Siehe https://github.com/symphonycms/symphony-2/issues/2704.

**Comment by animaux** [comment]
I could assign you fot this :)
